name: ta_monitor
description: Monitoring Tugas Akhir Flutter + Firebase

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0
  firebase_storage: ^11.6.0
  firebase_messaging: ^14.7.10 # DITAMBAHKAN

  # Fitur & Utility
  google_sign_in: ^6.2.1 # DITAMBAHKAN
  file_picker: ^6.2.0
  url_launcher: ^6.2.6
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/google_logo.png # DITAMBAHKAN
